version: "3.3"

services:
  persons-api-dev:
    container_name: persons-api
    image: golang:alpine
    volumes:
      - ./:/go/src/github.com/alexunjm/golang_persons-api
      - ../godeps:/go/pkg/mod/github.com
    working_dir: /go/src/github.com/alexunjm/golang_persons-api
    depends_on:
      - mysql
    command: >
      sh -c "go run main.go"
    environment:
      APP_PORT: 8080
      MYSQL_DRIVER: mysql
      MYSQL_USERNAME: alex
      MYSQL_PASSWORD: alex
      MYSQL_DATABASE: PERSONS
      MYSQL_PORT: 3306
      MYSQL_HOST: mysql
    ports:
      - 8080:8080
    networks:
      - api-network

  mysql:
    image: mysql:8.0.22
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: PERSONS
      MYSQL_USER: alex
      MYSQL_PASSWORD: alex
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - 3306:3306
    networks:
      - api-network

#Docker Networks
networks:
  api-network:
    driver: bridge

volumes:
  mysql_data:
